### ISSUE TITLE
New Viber Icon

### ISSUE THREAD

**Issue by JefersonFG** [linuxmint/mint-y-icons#10]
The present Viber icon is a dark orange telephone with a light orange background, which detracts from the iconic purple of the app. Can you make a new icon for Viber? I'd like to see some changes on the icon itself to modernize it, but the main change is to put the right color, and possibly the audio waves from the original icon.

**Comment by cranes-bill** [comment]
Quick **gimp**-fix for you:

![viber](https://cloud.githubusercontent.com/assets/5161278/21216043/4ffe3948-c2ad-11e6-8dde-e258c975b862.png)

**Comment by JefersonFG** [comment]
This looks amazing! Thanks!
