### ISSUE TITLE
Default GTK stock icons are dark and hard to see

### ISSUE THREAD

**Issue by Nihlus** [linuxmint/mint-y-icons#11]
Most of the GTK stock icons for actions are dark and very hard to see (as seen here in xed)
![image](https://cloud.githubusercontent.com/assets/2340428/17211119/c47f1b7e-54c7-11e6-967d-9d24d753d2e0.png)

Light versions of these icons should probably be included in Mint-Y.

**Comment by niberius** [comment]
Have the same issue. Are there any plans to include light version of this icons theme for better look in the dark GTK themes?

**Comment by JosephMcc** [comment]
We definitely want to do something about this. We just need to figure out the direction we want to go.

**Comment by tobia** [comment]
The Mint-Y icon theme looks amazing, many thanks to everyone involved!

A minor issue is that the indicator icons are black, which makes them hard to see on a black panel:

![icons](https://cloud.githubusercontent.com/assets/48756/24567280/4869d9e0-165d-11e7-95cd-0276fe0f43b2.png)

Mint-X has a Dark variant, where the indicator icons are light, but overall this theme is so much cooler! I just wanted to leave this here as a reminder to anybody who may work on color variants in the future.

**Comment by JosephMcc** [comment]
Mint-Y no longer falls back on Mint-X and now uses Adwaita instead so this is no longer an issue.
