### ISSUE TITLE
suggestions and ideas for Mint-Y icons, which still are the same as in Mint-X

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/mint-y-icons#13]
The places icons in Mint-Y are still the same as in Mint-X. As are other icons as well. So I think it would be good to have a place, which collects new ideas and suggestions for those icons.

So I'll start to collect, what was already proposed before.

**Places icons** suggestions:
(1) The places icons from Arc icons theme (https://github.com/horst3180/arc-icon-theme):
![bildschirmfoto vom 2016-10-31 11-48-51](https://cloud.githubusercontent.com/assets/8415124/19851808/0e84538c-9f60-11e6-8945-7d591f453094.png)
(2) The places icons from Oranchelo icon theme (https://github.com/OrancheloTeam/oranchelo-icon-theme):
![bildschirmfoto vom 2016-10-31 11-50-35](https://cloud.githubusercontent.com/assets/8415124/19852080/78935e48-9f61-11e6-824a-5e86930e04f8.png)

My opinion on those:
Both are looking good. But I think the icons in the middle of the folder in Arcs theme are a little bit too bright. I would make them a little bit darker like Oranchelo does, to get more contrast.

The next icons I want to talk about are the **folder emblems icons**. They should look similar to the icons in the middle of the places icons, for example:
![bildschirmfoto vom 2016-10-31 11-34-54](https://cloud.githubusercontent.com/assets/8415124/19852505/f96fe430-9f63-11e6-8eab-09ecb05f99a4.png)

Also I would suggest to move the icons in the middle of places icons to the right bottom (like Mint-X does). This way the emblem icons would look more consistent and cleaner:
![bildschirmfoto vom 2016-10-31 11-34-542](https://cloud.githubusercontent.com/assets/8415124/19852515/1a543840-9f64-11e6-9b93-bb52a16d6230.png)

**Comment by imarkskinner** [comment]
The Arc icons don't match the mint y theme at all. This is just my opinion of course but you look at every single icon specific to Mint Y, they're rounded edge squares and most have a single colour background with slight shadow and an icon of contrasting colour, often white. We should be aiming more along the lines of something akin the often favoured Faenza Mint look. https://www.gnome-look.org/content/show.php/Faenza-Mint?content=132681 I dont feel that Arc would be a huge step forward from the current places icons, just look at my panel launchers and tell me Nemo doesn't stand out like a sore thumb.
![image](https://cloud.githubusercontent.com/assets/1920963/23279904/05e01dd8-fa0f-11e6-8164-b46b0b13cc90.png)

**Comment by JosephMcc** [comment]
Well the same would be true in Mint-X. The bigger problem in the use case that you are showing is that Nemo relies on some folder icon instead of using an actual application icon of it's own. It's pretty much the only application that does that. It and other file managers.

**Comment by theel0ja** [comment]
@JosephMcc I think that Nemo should use Moka's icon named `nemo`.
[![nemo](https://raw.githubusercontent.com/snwh/moka-icon-theme/master/Moka/256x256/apps/nemo.png)](https://github.com/snwh/moka-icon-theme/blob/master/Moka/256x256/apps/nemo.png)

**Comment by JosephMcc** [comment]
Closing this since places icons have been added.
