### ISSUE TITLE
Mint-Y Computer Icon

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mint-y-icons#140]
Hi,

Could you change Computer icon for Mint-Y theme. For example, with Numix computer.

https://github.com/numixproject/numix-icon-theme/blob/master/Numix/16/devices/computer.svg

![mint-y-renkler](https://user-images.githubusercontent.com/1300133/39693752-c7668bfe-51ed-11e8-93ca-2d412aa82daf.png)

**Comment by JosephMcc** [comment]
We already plan to do something with it. Just haven't decided exactly what yet. Thanks for the suggestion.
