### ISSUE TITLE
icons too big in nemo

### ISSUE THREAD

**Issue by howdev** [linuxmint/mint-y-icons#170]
the zoom in nemo is 150% the preview and archive icons now are huge and bigger than folder icons at the same zoom level. And why there is no scaling between 100% and 150%? when 100% is too small on hidpi and 150% is too big. no 120% 140%?

**Comment by NikoKrause** [comment]
That's not an icon theme issue. That's nemo. And icon-view nemo in Mint 19.1 has gone through a lot of changes recently. If it's still an issue in 19.1 (you can try the beta), report it in the nemo repo.
