### ISSUE TITLE
Bluetooth icon on the Desktop panel is left out 

### ISSUE THREAD

**Issue by uncertainquark** [linuxmint/mint-y-icons#172]
As seen in the Linux Mint 19 Desktop panel, the bluetooth icon is not symbolic, unlike the rest of the status icons. The bluetooth icon thus stands out like a soaring thumb on the Desktop panel.

![03-mint-panel-bluetooth-icon](https://user-images.githubusercontent.com/22585732/42420418-222ce8d2-82e3-11e8-857b-43fa558dba14.png)

**Comment by JosephMcc** [comment]
That's because the bluetooth icon is part of the system tray. It doesn't use symbolics as it isn't a the same as a typical Cinnamon applet. Those icons are put there by the application that is using them.
