### ISSUE TITLE
Mint-Y-icons: many improvements in Linux Mint 19, but no update for Linux Mint 18.3 ?

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint-y-icons#180]
I tried Linux Mint Mate 19 on a live USB key. Just looking. Otherwise i still have Linux Mint Mate 18.3 installed on my HDD. I am currently using this 18.3. But i found many nice improvements with Mint-Y-icons in Linux Mint 19.

So here is my simple **question / issue**: would it be possible to make these updates available on the Mint Update for older Linux Mint versions?

I found many improvements in Linux Mint 19 icons that are still missing on Linux Mint 18.3:
- standard white notification icons in the "control panel" (bottom task bar, right zone)
- better, more coherent OSD icons for mate
- better, more coherent icons for places, applications, actions, etc.

P.S.: i did manage to copy this update from LM 19 to LM 18.3. I did it "by hand". I am just saying it would be nice if everyone else could receive it automatically, with Mint Update.

**Comment by NikoKrause** [comment]
The icons are not backported to older Mint versions. Not sure why, but it always has been like that and it's not just with Mint-Y, but also with Mint-X icons.
