### ISSUE TITLE
[DIscussion]Switch application icons from moka to newaita

### ISSUE THREAD

**Issue by otavioschwanck** [linuxmint/mint-y-icons#225]
Newaita:
https://www.gnome-look.org/p/1243493/

Pros:
Large applications set
maintain the visual identity of applications
Works well on cinnamon

Screenshoot:
![image](https://user-images.githubusercontent.com/9551316/53360365-238bbb80-3914-11e9-91ae-72a8ef9288bb.png)
![image](https://user-images.githubusercontent.com/9551316/53360417-3c946c80-3914-11e9-902b-35ff1d9cd698.png)

Its just a idea.

**Comment by pizzadude** [comment]
Nice icons, but I'm not sure they should be default.

**Comment by NikoKrause** [comment]
Mint-Y icons won't change to Newaita. Mint-Y is around for a few years now and in the past the decision was made to stick to Moka icons as base, because it was very popular back then.
It wouldn't be Mint-Y anymore.
