### ISSUE TITLE
Icon request: Brave browser

### ISSUE THREAD

**Issue by TheTatraTram** [linuxmint/mint-y-icons#229]
Brave is a Chromium-based browser which includes privacy features.

Icon:
![](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fblog.smei.org%2Fwp-content%2Fuploads%2F2018%2F04%2Fbrave_icon_shadow_300px-e1523448863715-1-e1523449287935.png&f=1)

**Comment by Sadi58** [comment]
This app icon is present now (ver. 1.3.3), maybe yould close it.
