### ISSUE TITLE
Standard icons for third-party applications

### ISSUE THREAD

**Issue by marcogiannini** [linuxmint/mint-y-icons#230]
Hi, I currently use a customized version of the icon theme Mint-Y that uses standard icons for third-party applications. Would it be possible for Linux Mint to have a set of icons of this type? Doing so would make it easier for new users to identify programs and save you the job of maintaining / adding new icons.

**Comment by NikoKrause** [comment]
Thanks a lot for the suggestion, but Mint already ships with a lot of icon themes and variation. Throwing more icons to the stack will be more work to maintain.
