### ISSUE TITLE
Icon Request - Mint-Y-Yellow

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint-y-icons#232]
It has been mentioned before since the Mint 19.1 Beta but has still not been implemented.
Filing an issue here for visibility and tracking.
Please build a set of Mint-Y-Yellow icons to compliment the Mint-X-Yellow set.
Screen shot below of the proposed set.

![Screenshot-from-2019-07-01-10-21-01](https://user-images.githubusercontent.com/45599505/60528195-ecfaee80-9cc1-11e9-8f0e-f460466e550a.png)

**Comment by antrrax** [comment]
I made these icons based on the Arc theme places.svg file and modified it to fit the Mint-Y theme.
https://github.com/horst3180/arc-icon-theme

My Custom Mint-Y-Icons:
http://www.mediafire.com/file/scshg17giwowd0j/Custom-mint-y-icons.zip/file

Unzip the Custom-mint-y-icons.zip file, inside the 'build-icons' folder are the custom icons, just copy all items from this folder to the 'Personal folder' > .icons

Mint-Y-Yellow
<a href="https://ibb.co/8zWpPnP"><img src="https://i.ibb.co/cbGH2K2/01.png" alt="01" border="0"></a>

Mint-Y-Dark-Yellow
<a href="https://ibb.co/YNHPfH7"><img src="https://i.ibb.co/QJypYyF/02.png" alt="02" border="0"></a>

Mint-Y-Royal
<a href="https://ibb.co/Kxh1phT"><img src="https://i.ibb.co/pjwmBwY/03.png" alt="03" border="0"></a>

Mint-Y-Dark-Royal
<a href="https://ibb.co/qYZVQ7k"><img src="https://i.ibb.co/b5fD9Qz/04.png" alt="04" border="0"></a>

places.svg - Yellow
<a href="https://ibb.co/rw8XG2z"><img src="https://i.ibb.co/mcZPC52/places1.png" alt="places1" border="0"></a>

places.svg - Dark Yellow
<a href="https://ibb.co/34mLcCf"><img src="https://i.ibb.co/2W3fdk8/places2.png" alt="places2" border="0"></a>

places.svg - Royal
<a href="https://ibb.co/xMS4kRb"><img src="https://i.ibb.co/FBbPrj1/places3.png" alt="places3" border="0"></a>

places.svg - Dark Royal
<a href="https://ibb.co/T4sCzXq"><img src="https://i.ibb.co/qNvZbGF/places4.png" alt="places4" border="0"></a>

Follow the script 'render_icons.sh' to generate Mint-Y icons places from the places.svg file in the 'src' an 'src-dark' folder

**Comment by antrrax** [comment]
Fixed some icon errors and posted to Gnome Look. My Themes and Custom Icons for mint-y:

[b]Mint-Y-Yellow Sky Themes and Icons:[/b]
https://www.pling.com/p/1322787/

<a href="https://ibb.co/CtfQcQY"><img src="https://i.ibb.co/CtfQcQY/0ydt.png" alt="01" border="0"></a> <a href="https://ibb.co/L6MHRqL"><img src="https://i.ibb.co/L6MHRqL/ydf.png" alt="01" border="0"></a> <a href="https://ibb.co/98cg1yc"><img src="https://i.ibb.co/98cg1yc/ydm.png" alt="01" border="0"></a>
 <a href="https://ibb.co/SvZjV5g"><img src="https://i.ibb.co/SvZjV5g/yt.png" alt="01" border="0"></a> <a href="https://ibb.co/ZX2pHTx"><img src="https://i.ibb.co/ZX2pHTx/yf.png" alt="01" border="0"></a> <a href="https://ibb.co/yhKgdt8"><img src="https://i.ibb.co/yhKgdt8/ym.png" alt="01" border="0"></a>

------------

[b]Mint-Y-Royal Blue Themes and Icons[/b]
https://www.pling.com/p/1322795/

<a href="https://ibb.co/4ZQXGyw"><img src="https://i.ibb.co/4ZQXGyw/rdf.png" alt="01" border="0"></a> <a href="https://ibb.co/r59GmWB"><img src="https://i.ibb.co/r59GmWB/rdm.png" alt="01" border="0"></a> <a href="https://ibb.co/84KCXWR"><img src="https://i.ibb.co/84KCXWR/rdt.png" alt="01" border="0"></a>
<a href="https://ibb.co/27n9PgX"><img src="https://i.ibb.co/27n9PgX/rf.png" alt="01" border="0"></a> <a href="https://ibb.co/B4YLrvR"><img src="https://i.ibb.co/B4YLrvR/rm.png" alt="01" border="0"></a> <a href="https://ibb.co/rfF6McK"><img src="https://i.ibb.co/rfF6McK/rt.png" alt="01" border="0"></a>

------------
