### ISSUE TITLE
Request: add in github the Mint-Y *.svg files for the places folder icons

### ISSUE THREAD

**Issue by antrrax** [linuxmint/mint-y-icons#234]
Please add in github the *.svg files for the places folder icons. So the community can create their own folder color variations, keeping the same style of Mint-Y's original icons.

For example, as I missed the yellow and royal blue icons for the folders I edited the places.svg file of the [Arc theme](https://github.com/horst3180/arc-icon-theme) and tried to make it match the theme that mint uses, and from the render_icons.sh script I generate the png icons. (But they are not exactly the same icons - they are just an approximation of the originals.)

My Custom Mint-Y-Icons:
**http://www.mediafire.com/file/scshg17giwowd0j/Custom-mint-y-icons.zip/file**

Unzip the Custom-mint-y-icons.zip file, inside the 'build-icons' folder are the custom icons, just copy all items from this folder to the 'Personal folder' > .icons

**### Update:**
New modified places.svg files >> 
https://www.mediafire.com/file/rlc6dc3j8tgqerk/New_SVG_places.tar.gz/file

Mint-Y-Royal Blue Themes and Icons
https://www.pling.com/p/1322795/

Mint-Y-Yellow Sky Themes and Icons:
https://www.pling.com/p/1322787/

**Comment by NikoKrause** [comment]
They have been added recently
