### ISSUE TITLE
Change Request - New Desktop Icon

### ISSUE THREAD

**Issue by otavioschwanck** [linuxmint/mint-y-icons#237]
![image](https://user-images.githubusercontent.com/9551316/68034863-43dcf880-fca1-11e9-8b7b-12c638f80fa4.png)

The current icon seems like the panel position is on top.  Would be nice to have a new one with the bar on bottom.

**Comment by NikoKrause** [comment]
You can move your panel to the top and add panels to the right and left edge of your screen.
