### ISSUE TITLE
Panel Icons not Scaled Properly

### ISSUE THREAD

**Issue by HopelessHarry** [linuxmint/mint-y-icons#239]
In 19.3 beta, both XFCE & Mate (not cinnamon) The Panel icons to the right of the panel are not scaled in sync with the panel items on the left. If the icons on the right of the panel are scaled to 16-18px, the icons on the left, including the Menu icon are tiny. And Vice-versa. 19.2 was fine. It is a Mint Y icons issue. I swapped out the Mint Y icons for both Qogir & Tela icons, & they scale perfectly.

**Comment by HopelessHarry** [comment]
OK. Thanks for looking into it Clem. Strangely the Mint Y theme looked fine in XFCE 19.2 on the same computer. It's only 19.3 were it looks odd.

**Comment by JosephMcc** [comment]
It's maybe not that strange. It's quite a change in XFCE 4.14 with the switch to Gtk3.

**Comment by HopelessHarry** [comment]
True. I wondered if that was the case. Maybe take a look at Zorin 15 Lite. That's also based on Ubuntu 18.3 with the XFCE 4.14 Desktop. They have managed to give the ability to scale the Monochrome Icons on the right, without it affecting the app icons on the left.
