### ISSUE TITLE
Cinnamon Menu Categories Education icon is wrong.

### ISSUE THREAD

**Issue by antrrax** [linuxmint/mint-y-icons#243]
Mint 19.03 x64
Cinnamon 4.4.8

I don't know if it was a change made on purpose or a mistake, but the icon used by the Education category in the Cinnamon Menu, is the science icon:
/usr/share/icons/Mint-Y/categories/24/applications-science.png

the education icon is this:
/usr/share/icons/Mint-Y/categories/24/applications-education.png

see the image
Toolbar> Mint button> right mouse click
Configure ...> Menu> Open the Menu editor

compare the education and science icons in the folder:
/usr/share/icons/Mint-Y/categories/24/

<a href="https://ibb.co/c3KNyfF"><img src="https://i.ibb.co/F3kBhZw/ksnip-20200122-141452.png" alt="ksnip-20200122-141452" border="0"></a>

**Comment by NikoKrause** [comment]
Yes, i think that's on purpose. Mint-Y has an applications-education icon, but most icon themes don't have such an icon, e.g. Mint-X and Gnome icons are missing this icon.
