### ISSUE TITLE
Icons make some flatpak installed apps UI unusable

### ISSUE THREAD

**Issue by cstamas** [linuxmint/mint-y-icons#244]
If you use LM 19.3 with ANY Mint-Y-* icons, flatpak installed Inkscape UI renders unusable. To "fix" (better: circumvent) it, you need to switch to some other NON Mint-Y icon set, and it works just fine.

More about it:
https://answers.launchpad.net/inkscape/+question/673715
https://forums.linuxmint.com/viewtopic.php?f=47&t=313434

**Comment by NikoKrause** [comment]
Hey, this shouldn't be no longer an issue with Inkscape 1.0, since it shippes with a set of symbolic icons.

![Inkscape symbolic icons](https://wiki.inkscape.org/wiki/images/c/c1/Themes.gif)
