### ISSUE TITLE
Brave icon (already in Moka icons)

### ISSUE THREAD

**Issue by ema2159** [linuxmint/mint-y-icons#259]
I was wondering why Brave's icon isn't in the icon set if it already exists in the Moka icon set. If you're alright with it, it should be easy to include so I think you shouldn't have much trouble.

Edit: It's already there. Why isn't it displaying by default?

**Comment by NikoKrause** [comment]
Hey, maybe the icon name, which is used by beave, has changed? You can check the .desktop file of brave for the icon name.

In Cinnamon you can do this by rightclicking on the brave entry in the menu, show on desktop, then rightclick on the brave desktop entry, open with texteditor.

**Comment by ema2159** [comment]
I'll do it as soon I'm home!

**Comment by ema2159** [comment]
@NikoKrause  this is what it contains:

Icon=brave-browser
Type=Application
Categories=Network;WebBrowser;

It's not very different from Firefox's:

Type=Application
Icon=firefox
Categories=GNOME;GTK;Network;WebBrowser;

The weird thing is that if I explore the /usr/share/icons/Mint-Y directory, this is the icon that I find for Brave (the correct one):
![image](https://user-images.githubusercontent.com/17773218/88358248-67fad100-cd2b-11ea-9554-2b13b2230a24.png)

The icon itself is called brave, so maybe it's that.

**Comment by ema2159** [comment]
Indeed that's the problem. So:
1. How do I change it system wide?
2. Will you issue a Mint update with this fix?
3. Shall I open an issue in Moka's repository?

**Comment by NikoKrause** [comment]
I'll create a PR soon. Have to rename all 'brave' icons in Mint-Y to 'brave-browser'. It probably won't be updated in Mint 20, so you will have to wait for Mint 20.1 or do it manually.

**Comment by ema2159** [comment]
For people that want a quick fix, you can issue the following command in `/usr/share/icons/Mint-Y/apps/` directory: `for dir in *; do sudo cp $dir/brave.png $dir/brave-browser.png; done`

**Comment by ViniciusBRodrigues** [comment]
> For people that want a quick fix, you can issue the following command in `/usr/share/icons/Mint-Y/apps/` directory: `for dir in *; do sudo cp $dir/brave.png $dir/brave-browser.png; done`

I tried it and I get this error:

cp: não foi possível obter estado de 'symbolic/brave.png': Arquivo ou diretório inexistente

(cp: it was not possible get status of "symbolic/brave.png": File or directory does not exist)

**Comment by ema2159** [comment]
@ViniciusBRodrigues oh, that's probably because the symbolic directory doesn't have any brave icon. Check in the other directories if after issuing the command, all the `brave` icons were changed to `brave-browser`.

**Comment by ViniciusBRodrigues** [comment]
> @ViniciusBRodrigues oh, that's probably because the symbolic directory doesn't have any brave icon. Check in the other directories if after issuing the command, all the `brave` icons were changed to `brave-browser`.

I don't know if I properly get it, but I changed it manually in the application. Many thanks
