### ISSUE TITLE
LMDE 4 - redshift icon not visible in taskbar

### ISSUE THREAD

**Issue by Mar-tux** [linuxmint/mint-y-icons#262]
Hello everyone, :)

since 14.08.2020 there is an issue with the icon for redshift. It is not visible anymore. There es a free space in the taskbar. Doing a right click on it, the redshift menu is opening.
So the program itself is working but the icon is missing. This error only occured when using the Mint-Y theme.

![redshift-icon-missing](https://user-images.githubusercontent.com/69798353/90393827-c8163600-e091-11ea-8510-910f95925806.png)

**Comment by smurphos** [comment]
Pretty sure this bug report belongs here - https://github.com/linuxmint/xapp/issues - as it's not a theme bug per-se.

Some more info
Issue seems to coincide with update to version 1.8.9 of xapps-common
Cinnamon version 4.6.7
redshift-gtk version - 1.12mint1
mint-y-icons version - 1.4.3

The icon is there, but not visible. It responds to right clicks appropriately.

~/.xsession-errors output associated with adding the icon

```
(xapp-sn-watcher:2405): GLib-GObject-WARNING **: 08:02:20.254: invalid uninstantiatable type '(null)' in cast to 'SnItem'

(xapp-sn-watcher:2405): GLib-GIO-CRITICAL **: 08:02:20.255: g_dbus_proxy_get_name: assertion 'G_IS_DBUS_PROXY (proxy)' failed

** (xapp-sn-watcher:2405): CRITICAL **: 08:02:20.255: Could get propertyies for (null): GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying

Cjs-Message: 08:02:45.104: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: :1.163 (org.x.StatusIcon.PID-2405-8)
```

I can't reproduce on main edition Mint20 so this does appear to be LMDE4 specific. On Mint 20 on launching redshift-gtk with a Mint-Y-Icon theme shows ~/.xsession-errors shows
`Cjs-Message: 07:47:27.706: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: redshift-gtk (org.x.StatusIcon.PID-691487-0)`

The icon shows OK for icon themes that are not using a symbolic - e.g Papirus, Mint-X etc.

**Comment by Mar-tux** [comment]
Hello smuphos,

thanks for your advice. I have posted the issue in den xapp-section.
