### ISSUE TITLE
GNOME Sound recorder has changed icon name

### ISSUE THREAD

**Issue by apandada1** [linuxmint/mint-y-icons#265]
OS: Linux Mint 20 Cinnamon Edition
GNOME sound recorder has changed icon name from `gnome-sound-recorder` to `org.gnome.SoundRecorder`
Here is its desktop file.
```
[Desktop Entry]
Type=Application
Name=Sound Recorder
Comment=Record sound via the microphone and play it back
# Translators: Do NOT translate or transliterate this text (this is an icon file name)!
Icon=org.gnome.SoundRecorder
Categories=GNOME;GTK;Audio;AudioVideo;
# Translators: Search terms to find this application. Do NOT translate or localize the semicolons! The list MUST also end with a semicolon!
Keywords=Audio;Application;Record;
Exec=gnome-sound-recorder
StartupNotify=true
X-Ubuntu-Gettext-Domain=gnome-sound-recorder
```
As a result, it is showing an inconsistent icon.

![Screenshot from 2020-11-02 13-02-48](https://user-images.githubusercontent.com/3063132/97841485-eba16200-1d0b-11eb-9d01-47eabc6712d0.png)

The icon which should be shown is this ![gnome-screen-recorder](https://github.com/linuxmint/mint-y-icons/raw/master/usr/share/icons/Mint-Y/apps/64/gnome-sound-recorder.png)

**Comment by apandada1** [comment]
I would be happy to fix it myself and send a pull request, for which I want to know something. If I add the line 
```
gnome-sound-recorder <-- org.gnome.SoundRecorder
```
to ` mint-y-icons/src/symbolic-apps-list`, will it automatically generate all the symbolic links to all the relevant directories in `/usr/share/icons`? Or, do I have to manually create symlinc in every relevant directory?

**Comment by NikoKrause** [comment]
After you added the line, run the script:
```
. /create-symbolic-link-from-list apps
```

**Comment by apandada1** [comment]
I created the symbolic links ([this commit](https://github.com/apandada1/mint-y-icons/commit/aac200516fcadfe847bf259d8ee826e7516d66f6)), and copied the modified directory to my `/usr/share/icons` to test it.
The icon changed, but for some reason, now the icon is blurred. I have attached some screenshots. How to fix this?
![3](https://user-images.githubusercontent.com/3063132/97959195-d0e6f000-1dd4-11eb-9c11-057a86ee34f6.png) ![2](https://user-images.githubusercontent.com/3063132/97959190-cf1d2c80-1dd4-11eb-8bd3-4fec73bd2801.png)
![1](https://user-images.githubusercontent.com/3063132/97959187-cd536900-1dd4-11eb-891f-29a48dde0884.png)
