### ISSUE TITLE
Broken Link Mint-Y icons

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/mint-y-icons#276]
com.jetbrains.IntelliJ-IDEA-Ultimate.png
is a broken link.
Several folders/sizes.

**Comment by NikoKrause** [comment]
Thanks for reporting. This should be fixed in Mint 20.1

https://github.com/linuxmint/mint-y-icons/commit/0874ce257e10721183857b6b9e1ec78e24dac371
