### ISSUE TITLE
Icon open lock key is different of icon close lock key

### ISSUE THREAD

**Issue by NerdsMaxx** [linuxmint/mint-y-icons#287]
### Icon open lock key is different of icon close lock key
![image](https://user-images.githubusercontent.com/69761459/111405624-9741c200-86af-11eb-8daa-cbfa7d8c0339.png)
![image](https://user-images.githubusercontent.com/69761459/111405648-9e68d000-86af-11eb-8d73-cbc2c926c0e2.png)

====================================================================================
### Open settings, then click accessibility, then go to tab keyboard. After this, activate visual indicator of Caps Lock and Num Lock.
====================================================================================

### Icon open num lock and closed num lock are normal.
![image](https://user-images.githubusercontent.com/69761459/111406142-7e85dc00-86b0-11eb-91fa-13a349256ec3.png)
![image](https://user-images.githubusercontent.com/69761459/111406153-82b1f980-86b0-11eb-9f17-ae0fcfb48a84.png)

====================================================================================

### Sorry for my english!

**Comment by NikoKrause** [comment]
Thanks for reporting. This is fixed by https://github.com/linuxmint/mint-y-icons/commit/c0d42288af98fa47e343d1fbfbddc8fee41c1f61?short_path=03fed6d#

**Comment by NerdsMaxx** [comment]
Thanks : ) !
