### ISSUE TITLE
Icon Request: Element, Notion, Zoom, Scratch, VSCodium

### ISSUE THREAD

**Issue by akirapink** [linuxmint/mint-y-icons#291]
element is an open source client for the matrix communication protocol. this software isn't available on the mint repo
![image](https://user-images.githubusercontent.com/33667869/131664446-f4baae2f-4c7b-455c-937a-782b51a1740b.png)
zoom is a free with premium plans popular video conferencing app distributed for many platforms. it's been heavily used in the last few years by schools during the covid-19 pandemic. this software is available on the mint repo.
![image](https://user-images.githubusercontent.com/33667869/131666138-806f6009-801b-4d01-a21d-e22d88ddc65a.png)
notion is a free with premium plans organization tool designed to be used by anyone to better organize themselves, from individuals to companies. this software is not officially supported on linux, but there are ports of it. old versions of which are available on the mint repo. it could also be used as a web app.
![image](https://user-images.githubusercontent.com/33667869/131665207-3652d8a0-71ae-4180-8926-0de0a793ea76.png)
scratch is a free website designed to teach young people the very, very basics of coding with blocks. while not officially supported on linux, web apps can allow for running it in it's own window.
![image](https://user-images.githubusercontent.com/33667869/131665488-4e09ce96-2518-4788-b579-9cca58add977.png)
vscodium is an open source fork of visual code studio that removes telemetry. this software is available on the mint repo
![image](https://user-images.githubusercontent.com/33667869/131665625-a65d11cd-6f9f-42d0-a881-8e73603790b1.png)
kame editor is an open source theme editor for the 3ds game console. this software isn't available on the mint repo

**Comment by luisrguerra** [comment]
<img src='https://svgshare.com/i/cKP.svg' height="256px" />
(.SVG vector image file at 32x32 resolution)

**Comment by luisrguerra** [comment]
<img src='https://svgshare.com/i/cLE.svg' height="256px" />
(.SVG vector image file at 32x32 resolution)

**Comment by Hokiper** [comment]
Just submitted a pull request (#451) to add Notion and Scratch icons.
Element, Zoom and VSCodium icons were added in the meantime since this issue was opened.
