### ISSUE TITLE
How can i join the mint-y-icons project?

### ISSUE THREAD

**Issue by PHPeon** [linuxmint/mint-y-icons#295]
I'd like to become a contributor for the mint-y-theme. I have this repo https://github.com/PHPeon/CustomIcons where you can check some of my sample icons

**Comment by PHPeon** [comment]
No one answers, nice

**Comment by JosephMcc** [comment]
If you are familiar with github, simply make PR's to get some feedback. Or open an issue talking about what you'd like to do. Not sure what else you are looking for.

**Comment by PHPeon** [comment]
I'd like to make icons for the project too, i left a link with my personal repo where I post various concept icons. I just hoped I'd be able to join

**Comment by JosephMcc** [comment]
I guess I'm a little confused by what you mean by "join". If you are submitting PR's to modify current icons, add new ones, etc. then you are contributing to the project. Work might be excepted or it might not. Maybe you will get feedback on changes the devs would like to see before merging.

Not exactly sure what you are going for here: https://github.com/linuxmint/mint-y-icons/pull/296
It looks like you are just trying to open a pull request for something that was already done by someone else.
