### ISSUE TITLE
GIMP icon redesign 

### ISSUE THREAD

**Issue by luisrguerra** [linuxmint/mint-y-icons#298]
The current Gimp icon in Mint-Y theme looks very strange, although the official Gimp icon is also kind of weird. I made this redesign adapted to the Moka style based on the [artwork](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/32x32/apps/gimp.svg) done by Alexey Varfolomeev for the Gimp icon in the open source theme [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme). A few months ago I made a similar proposal to the Zorin OS developers, the Zorin theme had a very strange Gimp icon too and I suggested they to use the Parpirus icon which was much better and followed the same style of their theme and they adopted it on Zorin OS 16.

![chrome_HtEYTclCjX](https://user-images.githubusercontent.com/31783838/145719682-c66e8a1a-44c8-4a75-96fd-760f24581679.png)
(current mint-y icon)

![wilber-big](https://user-images.githubusercontent.com/31783838/145720058-ff81e6e4-4b6a-4f32-bab6-d9203f41c3be.png)
(Official Gimp icon)

<br>

32x32 SVG vector image files hosted at svgur.com:
<img src='https://svgshare.com/i/cje.svg' width=32px height=32px ><img src='https://svgshare.com/i/cje.svg' width=128px height=128px >
<img src='https://svgshare.com/i/cmQ.svg' width=32px height=32px ><img src='https://svgshare.com/i/cmQ.svg' width=128px height=128px >

PNG Format:
![gimp 16](https://user-images.githubusercontent.com/31783838/145719570-937c0c66-8b58-454b-b492-61927d5d8280.png)![gimp](https://user-images.githubusercontent.com/31783838/145719547-eb35459c-b9a8-485e-9d1b-f40a5b9ca6c8.png)

![gimp-mint-y-v3 32x32](https://user-images.githubusercontent.com/31783838/145719640-0ba1e8ea-60ef-4e7a-842e-95c12f60fc57.png)![gimp-mint-y-v3](https://user-images.githubusercontent.com/31783838/145719643-405f721d-8f7b-46f9-942f-c9e939e84ee3.png)

**Comment by PHPeon** [comment]
It looks extremely good! But wouldn't it break the style of the mint-y-icons? I feel like there's too much detail that the user will not be able to appreciate

**Comment by luisrguerra** [comment]
> It looks extremely good! But wouldn't it break the style of the mint-y-icons? I feel like there's too much detail that the user will not be able to appreciate

I believe that a monochrome icon makes the GIMP icon almost unrecognizable. This is one type of icon that doesn't work to try to be too minimalist. If you Google it you can see that there aren't many monochrome versions of the GIMP icon because it's something very difficult to do.

**Comment by PHPeon** [comment]
Welp, can't say I'd make a better job than yee. Kudos to you again

**Comment by PHPeon** [comment]
Small request, i have this repo https://github.com/PHPeon/CustomIcons where I have previews of mint-y style icons, can you do a peer review/quality control?

**Comment by luisrguerra** [comment]
> Small request, i have this repo https://github.com/PHPeon/CustomIcons where I have previews of mint-y style icons, can you do a peer review/quality control?

I will take a look

**Comment by clefebvre** [comment]
I think the same as @PHPeon, I like the icon you made but it doesn't go with the style of mint-y app icons.

**Comment by PHPeon** [comment]
Sir @clefebvre I've submitted a pull request to the main branch from my fork of the mint y icons repository, mind checking it out?

**Comment by luisrguerra** [comment]
> I think the same as @PHPeon, I like the icon you made but it doesn't go with the style of mint-y app icons.

@clefebvre consider changing the current Linux Mint icon theme to the [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) icon theme. The Moka theme was discontinued 3 years ago and the Papirus icon theme fits very well on Linux Mint.

![vmplayer_FscYuU5aj7](https://user-images.githubusercontent.com/31783838/173163341-3c3b3c7b-59d8-4b62-a5be-11e6191f20b2.png)
