### ISSUE TITLE
Is this project active anymore? 

### ISSUE THREAD

**Issue by PHPeon** [linuxmint/mint-y-icons#301]
Not an issue and I'm probably just bothering people but this repo has been quiet for a very long time. Also none of recent pull requests have even been reviewed or checked thru

**Comment by JosephMcc** [comment]
Keep in mind they we are currently in the middle of a beta release. For a little while the focus will be only on fixing bugs that prevent releasing the final version.

**Comment by PHPeon** [comment]
👍
