### ISSUE TITLE
Wine, VLC and Software Manager icons redesign proposals

### ISSUE THREAD

**Issue by cassiojsl** [linuxmint/mint-y-icons#304]
The actual icons of these apps don't even remotely look like the original logos. I would like to propose to contributors that they redesign these icons so that they can approximate the original appearance.

**Wine**
<img src="https://user-images.githubusercontent.com/57728845/148304025-685e46f4-2fe0-4815-bd72-443ef38178c8.png" width="256">
<img src="https://user-images.githubusercontent.com/57728845/148240036-c5baec62-5ce1-4ff1-b5a0-779dd72411f1.png" width="256">

**VLC**
<img src="https://user-images.githubusercontent.com/57728845/148304024-a1c6eea0-e6af-4580-acd0-0483c7c8aa8c.png" width="256">
<img src="https://user-images.githubusercontent.com/57728845/148240041-885ece9d-941a-4be9-bfc0-d0c774b5b53c.png" width="256">

**Software Manager**
<img src="https://user-images.githubusercontent.com/57728845/148311211-4fe0a7fb-54f1-4a01-9dc1-31fb85fb9d4f.png" width="256">
<img src="https://user-images.githubusercontent.com/57728845/148310966-908b1e80-a612-4504-ba61-1ffeb3fa4086.png" width="256">

**Comment by PHPeon** [comment]
Dude I'm legit jealous. The Wine icon looks cutesy and all but the VLC one is next level. Kudos

**Comment by TPO100Cofficial** [comment]
personally, i think the software manager looks a bit too detailed
the mint logo in the bag wouldn't be good at small sizes, and the bag shape itself looks a bit too generic
but the wine and vlc icons look great!

**Comment by clefebvre** [comment]
Same as @TPO100Cofficial imo. VLC and Wine look good.
