### ISSUE TITLE
How can i create my own Mint-y icons?

### ISSUE THREAD

**Issue by OhaDerErste** [linuxmint/mint-y-icons#307]
Are there Templates for the background or anything else?

**Comment by PHPeon** [comment]
Just download a svg file and wipe the sheets of any color & detail. Here, take one from me https://github.com/PHPeon/CustomIcons

Open it in Inkscape or any svg editor of your choice, i reccomend you make multiple copies of a wiped-clean sheet so you won't have re-download a model each time you want to make an icon

**Comment by PHPeon** [comment]
I posted a file called sheet.svg just fy, download it and make copies of it for as many icons as you want

**Comment by junglized** [comment]
But how to add those icons to the theme? Do I need to manualy copy them into corresponding folders or is there an automation tool for that?

**Comment by PHPeon** [comment]
I don't know, i just make them. Never implemented on my own, you can consider submitting your creations to the repo and wait until they're published in the standard release package

**Comment by junglized** [comment]
Ah, so that's how it works. Just make icons, post request for incorporating them into the theme and hope for the best... I'll try it as a last resort method.

Nonetheless, thanks!

**Comment by clefebvre** [comment]
Note: Don't forget to modify the icon-name inside the svg file.
