### ISSUE TITLE
RIP Mint-Y-Icons

### ISSUE THREAD

**Issue by PHPeon** [linuxmint/mint-y-icons#308]
2015-2021

I'm sad to see this project coming to an end, it's my favorite Linux icon theme 😭

**Comment by Fantu** [comment]
why you told this? this project is still live

**Comment by PHPeon** [comment]
> why you told this? this project is still live

Hello sir, I've left a pull request on this repository some time ago, might wanna review it and aprove it if it fits?

**Comment by mtwebster** [comment]
A few days before that PR you had other things merged. Clearly it's not a dead project.

I'm sorry that PR hasn't been merged. There are only so many of us and things can get lost, particularly when that was right where we started prepping for a new Mint release - there has been a lot to do in multiple projects. This is relatively minor.

Posts like this are just childish and unhelpful. Pinging us from the PR itself would have been sufficient.

**Comment by Xmetalfanx** [comment]
just going through my notifications and found this ... also found **https://github.com/linuxmint/mint-y-icons/issues/301** that can probably be closed as an issue too
