### ISSUE TITLE
Question: Is this repo still active

### ISSUE THREAD

**Issue by tony1661** [linuxmint/mint-y-icons#310]
Hi all,

I haven't seen any commits since last year. Is this repo still active?

Also, I noticed that the Moka icon theme that this depends on is now archived and not accepting PRs. Is there something I am missing there as to why?

**Comment by tony1661** [comment]
@PHPeon thanks for letting me know!

**Comment by clefebvre** [comment]
really?

The icon theme is **not** abandoned.
We only commit fixes and improvements, no commits isn't necessarily bad news.
LMDE is a Mint subproject, always has been.
Both LMDE and Mint use this icon theme. In fact this is the default theme.

**Comment by tony1661** [comment]
@clefebvre since Moka is no longer available to commit to, are you guys running with that? Should I commit any changes to your repo?

**Comment by JosephMcc** [comment]
@tony1661 While a lot  of the icons come from the Moka theme, we don't depend on it. Pr's for changes to this theme should be made here.

**Comment by tony1661** [comment]
@JosephMcc thanks :) how often do the updates make it to the actually distro? Do we gotta wait until the next release?

**Comment by JosephMcc** [comment]
Most of the time things will get tagged and new release will be pushed out with each new Mint version. Sometimes you will get them more often if a problem is found and fixed right after a release or a serious issue is fixed mid release. It works that way for most of our stuff.

You don't see a lot of updates here because the theme is actually pretty solid and doesn't need a  bunch of changes.

**Comment by tony1661** [comment]
for sure. there are just a few apps I'd like to update. I guess once I update them I will need to wait for the next version of Mint for the updates to be brought in right?

Also, do you guys have a template and/or a design document that explains what rules we need to follow for contributions? Or should I just get the svg of one icon and use that as my "template" ?

**Comment by collinss** [comment]
@tony1661 if you don't want to wait, you could always build and install it yourself (or just copy the updated icons to the proper locations on your local machine)

**Comment by tony1661** [comment]
@collinss for sure. I was more wondering how the whole process works 🙂
