### ISSUE TITLE
Can I use it in my OS?

### ISSUE THREAD

**Issue by yap241986** [linuxmint/mint-y-icons#311]
Can I use this icons in my Linux distro?

**Comment by yusi1** [comment]
Yes, this is what you need to do:
Clone the repo with `git clone https://github.com/linuxmint/mint-y-icons`
Change dir into the `mint-y-icons/usr/share/icons` folder
Do `cp -r * ~/.local/share/icons`
Done! Now you can select the icons in the settings for your DE
