### ISSUE TITLE
Icon Request: Can you add an icon for kotlin?

### ISSUE THREAD

**Issue by vadimk1337** [linuxmint/mint-y-icons#316]
These are files called .kt, is the official language for developing android applications and it doesn't have an icon.
you can see how yaru developers did it:
https://github.com/ubuntu/yaru/issues/3686

Type row: Kotlin source code (text/x-kotlin)

**Comment by PHPeon** [comment]
I will try and make one today for you but just as a preview sample the repository has to approve everything

**Comment by nazar1ua** [comment]
I also will try to draw this icon
