### ISSUE TITLE
Mint-y-Dark tray icons are forcing panel into 30px+ mode

### ISSUE THREAD

**Issue by calexil** [linuxmint/mint-y-icons#33]
![screenshot at 2017-07-03 13-42-28](https://user-images.githubusercontent.com/3487071/27804711-6ef5e2a8-5ffe-11e7-899a-a374487d6bfb.png)

Using the elementary dark icon set, works with mint-x themes fine.

**Comment by JosephMcc** [comment]
We have no mint-y-dark icon set.

**Comment by Xmetalfanx** [comment]
I am not seeing what is meant (I do think some icons seems a TAD large i suppose) but I think the original poster may have meant icons (with certain icon packages) seem large when using the mint-y dark THEMES ... I am just guessing at that, to clarify for the Mint team though

**Comment by calexil** [comment]
@Xmetalfanx  yeah its a theming issue, caused by the gtk2-3 update. Im tracing the issue in mint-y-dark(the affected theme)

**Comment by calexil** [comment]
this is not resolved, and the tray icons are all over the place in mint 19 MATE now. 

![Screenshot at 2019-04-08 18-42-36](https://user-images.githubusercontent.com/3487071/55761730-5a361500-5a2e-11e9-850f-840ade4e31f3.png)

**Comment by calexil** [comment]
this is using the elementary icon theme and MATE.

probably wrong place to report.
