### ISSUE TITLE
mint-y-aqua not aqua anymore

### ISSUE THREAD

**Issue by staticf0x** [linuxmint/mint-y-icons#332]
Fedora 37, in 1.6.5-1 the mint-y-aqua icons are not aqua anymore, they're yellowish. Mint-x-aqua though are aqua. Downgrading to 1.6.1-1 helps temporarily.

**Comment by itkfm** [comment]
You might be looking for https://github.com/linuxmint/mint-y-icons-legacy

**Comment by clefebvre** [comment]
This is fixed on master.
