### ISSUE TITLE
Create Mint-Y-Basic style without application themes

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint-y-icons#337]
Instead of having Breeze, Numix and Yaru icons, it would be better to create an icon variant without application themes like in Yaru, but keeping some application icons like: Transmission, Network, Terminal, System Monitor, category icons, cs -icons, mate and xfce settings. With the yellow paste color of Mint-L-Yellow.

**Comment by clefebvre** [comment]
Please feel free to fork mint-y and create your own variant.

**Comment by Initu-Castilhos** [comment]
> Por favor, sinta-se livre para fork mint-y e criar sua própria variante.

Thanks for the reply, I will do that.
