### ISSUE TITLE
Mint-Y icons at 96px have a "phantom" strip

### ISSUE THREAD

**Issue by AchillesBoi** [linuxmint/mint-y-icons#339]
The new Mint-Y icons that are set to be released with Mint 21.2 do not have a colored strip in the lower-right corner anymore. This is true for all sizes except 96px, where the strip was not cleaned out properly and you can still see a part of that strip in the lower-center of the folder, a few pixels wide. This affects all colors, not just yellow.

![Screenshot from 2023-04-21 16-45-10](https://user-images.githubusercontent.com/55808665/233741561-515d50a0-f2b7-416c-9674-b9ef947e7085.png)

**Comment by AchillesBoi** [comment]
Hello? Anyone home?

**Comment by clefebvre** [comment]
Well spotted.

Fixed by https://github.com/linuxmint/mint-y-icons/commit/340ff0f54695911c7ab5aec3d00b451a54afe3ae and https://github.com/linuxmint/mint-y-icons/commit/e8611ff137d05db8a76910be74a865b21bc09d00
