### ISSUE TITLE
update touchpad gestures icon

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint-y-icons#355]
I just noticed that the icon I [proposed](https://github.com/linuxmint/cinnamon/pull/11674) for gestures, did not have a rounded border like the ones in the Mint-Y/Mint-L themes.

[@mtwebster ](https://github.com/linuxmint/mint-y-icons/commit/324596918fe6dcd34319d84840d475cf08f55461) corrected it by adding a margin,  but by reducing the icon, the definition of the icon is lost.

- Here is the corrected icon:  [touchpad gestures.svg.zip](https://github.com/linuxmint/mint-y-icons/files/12231081/touchpad.gestures.svg.zip)

**Comment by haggen88** [comment]
probably missing a dark border like the other icons

**Comment by mtwebster** [comment]
Merged https://github.com/linuxmint/mint-y-icons/commit/cc8f1576f0a992964c199c05770ad891aad81369

I had to add a black border around it before it looked right.
