### ISSUE TITLE
Mint-Y-Dark icon pack missing

### ISSUE THREAD

**Issue by XXLuigiMario** [linuxmint/mint-y-icons#363]
Hello, I've just upgraded my system from LMDE 5 to LMDE 6 and noticed my icons looked off. After checking the theme manager, I noticed my icon theme, Mint-Y-Dark had been replaced with a default one, while still set to "Mint-Y-Dark". It seems that during the upgrade I received an update to mint-y-icons 1.6.7 which no longer offers said pack, as a result of 8b395de6e09621ee175274e5b8d784cf8798bae6.

My question is, what prompted this removal? I can't seem to find a suitable replacement, and I'm using Mint-Y-Dark for both my application and desktop themes.

**Comment by clefebvre** [comment]
Hi @XXLuigiMario,

The "Mono icons" paragraph at https://linuxmint.com/rel_victoria_cinnamon_whatsnew.php explains the change.

Fullcolor icons are now inherited from Adwaita, they're colorful as opposed to monochrome.

Applications are encouraged to switch to symbolic icons to properly supported all possible themes.
