### ISSUE TITLE
Oversized "class" icon

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint-y-icons#364]
In system-config-printer: 
![oversized](https://github.com/linuxmint/mint-y-icons/assets/118076740/c621862b-6485-45e4-b4b3-be252102ef93)
so maybe there's some bigger icon still present in the mint-y-icons which is being used instead of the Adwaita? or how? ref: [mint21.2-beta#54](https://github.com/linuxmint/mint21.2-beta/issues/54)

Note: not sure if "class" is the real icon name, anyway, that's the icon for class in system-config-printer here.

**Comment by haggen88** [comment]
When searching for icons in the "edit menu" option, that icon appears as 'gtk-dnd-multiple' and in the [wiki](https://commons.wikimedia.org/wiki/File:Stock-dnd-multiple.svg) as "Stock-dnd-multiple".

**Comment by clefebvre** [comment]
This is not a bug in mint-y or mint-l. It's reproducible with Adwaita directly.

**Comment by carlosmintfan** [comment]
@clefebvre Where should I report it?
