### ISSUE TITLE
Wrong Qt5 theme

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint-y-icons#366]
Qt5 uses the green Mint-Y theme by default, instead of the sand, which is the default in Mint 21.2!
See:
![wrong qt5 theme 2023-11-15 13-17-09](https://github.com/linuxmint/mint-y-icons/assets/118076740/cba0de05-1b57-4b89-9dce-d8f1a1602aba)

**Comment by clefebvre** [comment]
Fixed in mint-artwork 1.8.0.

**Comment by carlosmintfan** [comment]
@clefebvre Thanks! Is mint-artwork not available on github?
