### ISSUE TITLE
Icon request: LibreWolf, Obsidian

### ISSUE THREAD

**Issue by akirapink** [linuxmint/mint-y-icons#370]
LibreWolf is a fork of Firefox with a focus on privacy and security
![image](https://github.com/linuxmint/mint-y-icons/assets/33667869/0c91d5ba-b48c-433c-b8c7-4cb1550ef43d)
Obsidian is a notetaking application based on Markdown
![image](https://github.com/linuxmint/mint-y-icons/assets/33667869/6b86483d-91d8-4934-8a53-7cff738f85c2)

**Comment by PHPeon** [comment]
> LibreWolf is a fork of Firefox with a focus on privacy and security ![image](https://private-user-images.githubusercontent.com/33667869/287274780-0c91d5ba-b48c-433c-b8c7-4cb1550ef43d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDQxODAsIm5iZiI6MTcwMzAwMzg4MCwicGF0aCI6Ii8zMzY2Nzg2OS8yODcyNzQ3ODAtMGM5MWQ1YmEtYjQ4Yy00MzNjLWI4YzctNGNiMTU1MGVmNDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE2MzgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YWIwYjExMzQxYTVmZWM2YjRhZTYwY2I5MTM1ZjU2MGU3ZjBiOGM2MDllZmRmZDg0N2JjMGE2YTNjZjNiYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aUGV5nIdcedA5etCCKaWcbS3mY7brkGZOzANKDBGD04) Obsidian is a notetaking application based on Markdown ![image](https://private-user-images.githubusercontent.com/33667869/287275016-6b86483d-91d8-4934-8a53-7cff738f85c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDQxODAsIm5iZiI6MTcwMzAwMzg4MCwicGF0aCI6Ii8zMzY2Nzg2OS8yODcyNzUwMTYtNmI4NjQ4M2QtOTFkOC00OTM0LThhNTMtN2NmZjczOGY4NWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE2MzgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMGI4NDI2OGM2NGQ5NTMwMmRmZjNlZGRmYzMzNmJhMzdkZmUwYTI3YTViNGE2ZjNkNDlmNGJkM2Q1OTYwMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sTgJhnRd4odyFdyYrkXbAzStB4w2ykPFWysQTAFJiQQ)

Hold on buddy i got you i will send you a link once they're done and some photos

**Comment by PHPeon** [comment]
@akirapink there you go bud

![Screenshot from 2023-12-19 19-07-33](https://github.com/linuxmint/mint-y-icons/assets/87318244/8caeee0b-c66e-4b2e-9647-a1a21eeee6ef)
