### ISSUE TITLE
Pale Moon Icons

### ISSUE THREAD

**Issue by Ascrod** [linuxmint/mint-y-icons#40]
As I originally posted in linuxmint/mint-y-theme#75, the Mint-Y icon theme appears to override the icons for Pale Moon, a web browser I have installed, with a completely different icon from Battle.net, which is not related to the browser in any way.

**Comment by wolfbeast** [comment]
See also PR #39

**Comment by JosephMcc** [comment]
Addressed by https://github.com/linuxmint/mint-y-icons/pull/39
