### ISSUE TITLE
"Back in Time" Icon missing

### ISSUE THREAD

**Issue by Piiit** [linuxmint/mint-y-icons#43]
There is no icon for this application. The one used is a stock icon (save as...) I guess. 
This brings two problems:
* It is too dark and is therefore hard to see on the task list
![auswahl_145](https://user-images.githubusercontent.com/6096063/33075926-6508c724-cecb-11e7-9144-21b5a34c9686.jpg)
* It is blurry (using alt+tab)
![arbeitsflache 1_146](https://user-images.githubusercontent.com/6096063/33076096-fce97156-cecb-11e7-968c-30f5afb44d9e.jpg)

**Comment by NikoKrause** [comment]
Is there an official icon from back in time?
Can you find out, what's how's the icon name called, which is used by back in time?

Maybe the Deja Dup icon can be used for it? https://github.com/linuxmint/mint-y-icons/blob/master/usr/share/icons/Mint-Y/apps/96/deja-dup.png

**Comment by Piiit** [comment]
@NikoKrause The deja-dup icon looks good. I think backintime does not have its own icon, thou... see https://github.com/bit-team/backintime/blob/master/common/backintime.desktop. Another idea would be to use their github logo (https://github.com/bit-team), but that would not fit into mint-y-icons IMO. I would go with the deja-dup as you say.

**Comment by Piiit** [comment]
The missing backintime icon is an open issue: https://github.com/bit-team/backintime/issues/215
