### ISSUE TITLE
No icons for logout / quit.

### ISSUE THREAD

**Issue by besser82** [linuxmint/mint-y-icons#52]
I really like the icon theme, but the icons for shutdown and quit in the Cinnamon (applications) menu are missing and thus inherited from Mint-X-icons.  There seems to be an icon for locking the screen, but the combination with the two others from Mint-X-icons doesn't look nice.

**Comment by JosephMcc** [comment]
You need to poke your head in artwork channel on slack. We just discussed this yesterday :)

**Comment by besser82** [comment]
@JosephMcc Ahh, okie…
