### ISSUE TITLE
Steam System Tray icon blurry

### ISSUE THREAD

**Issue by chase9** [linuxmint/mint-y-icons#54]
![screenshot from 2017-11-23 11-43-44](https://user-images.githubusercontent.com/6013163/33184741-c3f418a0-d043-11e7-8529-2b5848752b16.png)

**Comment by JosephMcc** [comment]
Mint-Y doesn't supply this icon.

**Comment by chase9** [comment]
@JosephMcc Where does this icon come from? Could it be resolved by adding a Steam icon to Mint-Y?
