### ISSUE TITLE
Suggestion:  Mint-y dark and darker icons

### ISSUE THREAD

**Issue by otavioschwanck** [linuxmint/mint-y-icons#56]
Some apps are ugly using Mint y darker theme and mint-y icons, like transmission:
![captura de tela de 2017-12-01 10-27-14](https://user-images.githubusercontent.com/9551316/33482866-3b1974c2-d682-11e7-88f5-2826347c04f5.png)

On Save As dialog in cinnamon in "Outros Locais" have a black plus on black background:
![captura de tela de 2017-12-01 10-28-23](https://user-images.githubusercontent.com/9551316/33482967-a5586a82-d682-11e7-870a-43742c35095f.png)

For example, papirus icon solve both of problems.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/mint-y-icons/issues/11
