### ISSUE TITLE
Icon improvements/ideas for Linux Mint 19

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/mint-y-icons#57]
- [ ] VLC
Right now it looks like this:
![vlc](https://user-images.githubusercontent.com/8415124/33496933-57b1f8ee-d6cc-11e7-8c21-0b60ea27f669.png)
Use the VLC cone instead.

- [ ] PIA Manager
PIA icon looks like this:
![pia-manager](https://user-images.githubusercontent.com/8415124/33497087-ecb3867e-d6cc-11e7-993e-cb617e78626c.png)
The androidstudio icon can be used as a base for the Mint-Y PIA icon:
![androidstudio](https://user-images.githubusercontent.com/8415124/33497066-db0d17c8-d6cc-11e7-883e-7f367da98011.png)

**Comment by clefebvre** [comment]
Cool, PRs welcome :)
