### ISSUE TITLE
Combine mint-y with arc-icon-theme

### ISSUE THREAD

**Issue by irondave** [linuxmint/mint-y-icons#9]
Use the icons arc replacing the old icons mint-x still in mint-y.
https://github.com/horst3180/arc-icon-theme

**Comment by NikoKrause** [comment]
Are you still open for new suggestions regarding flat icons?
I think https://github.com/OrancheloTeam/oranchelo-icon-theme has some cool flat icons, excepecially the places icons.

**Comment by NikoKrause** [comment]
I think my second comment was deleted? I thought I have posted an image of the places icons of Oranchelo. Can comments be deleted without me getting informed. Or have I forgotten to press the comment button?

**Comment by JosephMcc** [comment]
I'm going to close this one since it's pretty much the same as https://github.com/linuxmint/mint-y-icons/issues/13
